### ISSUE TITLE
Error when Run pre_remediation RHEL9-CIS audit

### ISSUE THREAD

**Issue by tpaiii3** [ansible-lockdown/RHEL9-CIS-Audit#18]
I excuted the ansible to run https://github.com/ansible-lockdown/RHEL9-CIS including Audit run. I found this error. 

![Code_ZQBGod7r2X](https://user-images.githubusercontent.com/85722230/224534419-1553f5ad-56e7-42d0-8667-d77a289defa5.png)

**Comment by uk-bolly** [comment]
hi @tpaiii3 

Thank you for raising this issue, I have isolated this issue and will be fixing merging this shortly.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @tpaiii3 

Happy to say this merge has taken place already. All working as expected. Thank you again for taking the time to highlight this issue.

Thanks

uk-bolly
