### ISSUE TITLE
5.6.1.3 regex typos

### ISSUE THREAD

**Issue by boris-stojnev** [ansible-lockdown/RHEL9-CIS-Audit#22]
Rule https://github.com/ansible-lockdown/RHEL9-CIS-Audit/blob/devel/section_5/cis_5.6/cis_5.6.1.3.yml

first check
title: 5.6.1.3 | Ensure password expiration warning days is 7 or more, may give false alarm if PASS_WARN_AGE has more then 2 digits.

I would suggest replacing line 9 
`- '!/^PASS_WARN_AGE\s*[1-6]/'`
with
`- '!/^PASS_WARN_AGE\s*[1-6]$/'`

second check in the same rule
title: 5.6.1.3 | Ensure password expiration warning days is 7 or more | check_users, I would say it's a typo mistake line 24 has one ] extra and on line 25 [ is missing:
```
- '/^.*:([7-9]|[1-9][0-9]{1,}])$/'
- '!/^.*:1-6]$/'
```
replace with
```
- '/^.*:([7-9]|[1-9][0-9]{1,})$/'
- '!/^.*:[1-6]$/'
```

**Comment by uk-bolly** [comment]
hi @boris-stojnev 

Thank you for feeding back and helping us to continue to improve this content. I have raised a new branch sept23 that contains the fix which i have extended slightly.
Please let me know if this works now as expected.

many thanks

uk-bolly

**Comment by boris-stojnev** [comment]
Hi @uk-bolly ,

Yes, it's fine. 
What about second check I mentioned, `check_users_MAX_DAYS`

Thank you.

**Comment by uk-bolly** [comment]
hi @boris-stojnev 

Apologies, completely missed this. This is now added.

regards

uk-bolly
