### ISSUE TITLE
run_audit setup finds ORACLE and not RHEL

### ISSUE THREAD

**Issue by moljnir** [ansible-lockdown/RHEL9-CIS-Audit#23]
**Describe the Issue**
On Oracle 9U2 (at least), running the RHEL9-CIS-AUDIT extracts os_vendor from `hostnamectl` , which returns ORACLE and not RHEL.
Thus when one sets AUDIT_CONTENT_LOCATION, rather than RHEL9 being inserted, ORALCE9 is instead. If one has cloned the repository, it will be /path/RHEL9-CIS-AUDIT, and not /path/ORACLE9-CIS-AUDIT

**Expected Behavior**
Neither /etc/os-release nor hostnamectl contain and reference to RHEL. At this time, there should be a mapping to identify Oracle as RHEL, as for the future, who knows. If one maps ORACLE to RHEL , then it will functions as intended.

**Actual Behavior**
The following shows how the run_audit script identifies the os family

++ hostnamectl
++ cut -d : -f2
++ grep Oper
++ awk '{print $1}'
++ tr a-z A-Z
+ os_vendor=ORACLE
++ awk '-F"' '{print $2}'
++ cut -d . -f1
++ grep -w VERSION_ID= /etc/os-release
+ os_maj_ver=9
+ audit_content_version=ORACLE9-CIS-Audit
+ audit_content_dir=/home/opc/ORACLE9-CIS-Audit

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.2
- Host Python Version:  Python 3.11.12
- Ansible Server Python Version: Python 3.9.16
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
In run_audit, have an associative array mapping ORACLE -> RHEL (only as it eliminates having a conditional)

**Comment by uk-bolly** [comment]
hi @moljnir 

Thank you for feeding back and helping us to continue to improve this content. I have raised a new branch sept23 
Please let me know if this works now as expected.

many thanks

uk-bolly

**Comment by moljnir** [comment]
> hi @moljnir
> 
> Thank you for feeding back and helping us to continue to improve this content. I have raised a new branch sept23 Please let me know if this works now as expected.
> 
> many thanks
> 
> uk-bolly

Hi, 

This now runs cleanly on Oracle Linux 9 (U2) as cloned from this branch.

(Should I have "closed" this, or is this comment sufficient ?)

Regards
