### ISSUE TITLE
Missing rhel9cis_rule_5_1_9 from vars/CIS.yml

### ISSUE THREAD

**Issue by moljnir** [ansible-lockdown/RHEL9-CIS-Audit#24]
**Describe the Issue**
When running the run_audit.sh, it fails with the following error:

Error: could not read json data in /home/opc/ORACLE9-CIS-Audit/section_5/cis_5.1/cis_5.1.8_9.yml: template: test:31:11: executing "test" at <.Vars.rhel9cis_rule
_5_1_9>: map has no entry for key "rhel9cis_rule_5_1_9"

**Expected Behavior**
There should be no non-existent variables referenced in conditional statements.

**Actual Behavior**
{{ if .Vars.rhel9cis_rule_5_1_9 }}
  /etc/at.deny:
    title: 5.1.9 | Ensure at is restricted to authorized users
    exists: false
    meta:

Since the variable has not been defined, it is not possible to evaluate the conditional statement.

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.15.2
- Host Python Version: Python 3.11.12
- Ansible Server Python Version: Python 3.9.16
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Add rhel9cis_rule_5_1_9 to the defaults to the CIS.yaml file.

**Comment by uk-bolly** [comment]
hi @moljnir 

Thank you for feeding back and helping us to continue to improve this content. I have raised a new branch sept23 
Please let me know if this works now as expected.

many thanks

uk-bolly

**Comment by moljnir** [comment]
> hi @moljnir
> 
> Thank you for feeding back and helping us to continue to improve this content. I have raised a new branch sept23 Please let me know if this works now as expected.
> 
> many thanks
> 
> uk-bolly

**Comment by moljnir** [comment]
Hi, @uk-bolly 

Yes this runs without errors; the variable in the condition is now defined.

Regards.
