### ISSUE TITLE
Duplicate key detected: 'package: vsftp'. 

### ISSUE THREAD

**Issue by cobrin** [ansible-lockdown/RHEL9-CIS-Audit#34]
**Describe the Issue**
Manually running Audit on freshly built RHEL 9.4 system generates warning message

```
[root@rhel94-test02 ~]# /opt/RHEL9-CIS-Audit/run_audit.sh

## Pre-Checks Start

OK - Audit binary /usr/local/bin/goss is available
OK - Goss is installed and version is ok (0.4.7 >= 0.4.4)
OK - /opt/RHEL9-CIS-Audit/goss.yml is available

## Pre-checks Successful

#############
Audit Started
#############

2024-06-01T23:42:43Z [WARN] Duplicate key detected: 'package: vsftp'. The value from a later-loaded goss file has overwritten the previous value.
    "summary": {
        "failed-count": 90,
        "skipped-count": 12,
        "summary-line": "Count: 639, Failed: 90, Skipped: 12, Duration: 35.228s",
        "test-count": 639,
Completed file can be found at /opt/audit_rhel94-test02-CIS-RHEL9_1717285363.json
###############
Audit Completed
###############
```

**Expected Behavior**
No warnings generated

**Actual Behavior**
The files `section_2/cis_2.3/cis_2.3.1_4.yml` and `section_2/cis_2.2/cis_2.2.6.yml` contain a duplicate key `vsftp`

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: devel

**Possible Solution**
`sed -i 's/vsftp/ftp/' section_2/cis_2.2/cis_2.2.6.yml`

**Comment by uk-bolly** [comment]
hi @cobrin 

Thank you for raising this issue, this fix has been merged into the benchmark branch and will be merged into devel later today.

Many thanks

uk-bolly
