### ISSUE TITLE
Missing meta/main.yml causes galaxy-install to fail in roles/requirements.yml 

### ISSUE THREAD

**Issue by gocyclones** [ansible-lockdown/RHEL9-CIS-Audit#37]
Describe the Issue
This role does not appear to have a meta/main.yml file.

Expected Behavior
Starting galaxy role install process

changing role RHEL9_cis_audit from to unspecified
Actual Behavior
[WARNING]: - RHEL9-CIS-Audit was NOT installed successfully: this role does not appear to have a meta/main.yml file.

Control(s) Affected
Using it in a project.

Environment (please complete the following information):

not relevant here.

Additional Notes
Anything additional goes here

Possible Solution
Add file meta/main.yml.

**Comment by uk-bolly** [comment]
hi @gocyclones 

This repository is not an ansible role i'm afraid. If you are looking for the ansible role that will utilise this repository. 
[RHEL9-CIS](https://github.com/ansible-lockdown/RHEL9-CIS)
That will give you the ansible playbook, to run audit and remediate (bring the system into compliance based upon your requirements).

I hope that helps.

uk-bolly
